/**
 * unit-generator.ts — Generate systemd .timer + .service units from job definitions.
 *
 * Each job produces two files:
 *   poseidon-{project}-{job}.timer   — When to fire
 *   poseidon-{project}-{job}.service — What to run (via job-runner.ts)
 */

import { join } from "path";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { homedir } from "os";
import type { QualifiedJob } from "./types";
import { cronToOnCalendar } from "./cron-parser";

const UNIT_PREFIX = "poseidon-sched";

export function unitName(job: QualifiedJob): string {
  return `${UNIT_PREFIX}-${job.project_id}-${job.id}`;
}

export function generateTimerUnit(job: QualifiedJob): string {
  const onCalendar = cronToOnCalendar(job.schedule);
  const persistent = job.persistent ? "true" : "false";

  return `# Generated by Poseidon Scheduler — do not edit manually
# Job: ${job.qualified_id}
# Schedule: ${job.schedule}
# Purpose: ${job.purpose}
[Unit]
Description=Poseidon Scheduler: ${job.name} (${job.qualified_id})

[Timer]
OnCalendar=${onCalendar}
Persistent=${persistent}
${job.timezone !== "UTC" ? `# Timezone: ${job.timezone} (systemd uses system tz; cron handles conversion)` : ""}

[Install]
WantedBy=timers.target
`;
}

export function generateServiceUnit(job: QualifiedJob, poseidonDir: string): string {
  const jobRunnerPath = join(poseidonDir, "scheduler", "job-runner.ts");
  const jobConfigJson = JSON.stringify({
    job_id: job.qualified_id,
    project_id: job.project_id,
    command: job.command,
    type: job.type,
    working_dir: job.working_dir || join(homedir(), "projects", job.project_id),
    timeout: job.timeout,
    secrets_required: job.secrets_required,
    concurrency: job.concurrency,
  });

  // Base64 encode to avoid shell escaping issues
  const configB64 = Buffer.from(jobConfigJson).toString("base64");

  return `# Generated by Poseidon Scheduler — do not edit manually
# Job: ${job.qualified_id}
[Unit]
Description=Poseidon Job: ${job.name} (${job.qualified_id})

[Service]
Type=oneshot
ExecStart=/usr/local/bin/bun ${jobRunnerPath} --config-b64 ${configB64}
WorkingDirectory=${job.working_dir || join(homedir(), "projects", job.project_id)}
Environment=POSEIDON_DIR=${poseidonDir}
TimeoutStartSec=${job.timeout}

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
`;
}

export interface GenerateResult {
  timerPath: string;
  servicePath: string;
  unitName: string;
}

export function writeUnits(
  job: QualifiedJob,
  poseidonDir: string,
  unitDir?: string,
): GenerateResult {
  const dir = unitDir || join(homedir(), ".config", "systemd", "user");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const name = unitName(job);
  const timerPath = join(dir, `${name}.timer`);
  const servicePath = join(dir, `${name}.service`);

  writeFileSync(timerPath, generateTimerUnit(job));
  writeFileSync(servicePath, generateServiceUnit(job, poseidonDir));

  return { timerPath, servicePath, unitName: name };
}
